window.GOOD_MEALS = [
  {
    slug: "pollo-al-curry",
    name: "Pollo al curry",
    crop: 0,
    image: "assets/meals/pollo-al-curry.JPG",
    calories: 610,
    protein: "50g",
    carbs: "39g",
    fat: "26g",
    labels: ["Pollo", "Alto en proteína", "Comida especiada"],
    description: "Arroz blanco con delicioso pollo al curry.",
    ingredients: [
      "Arroz blanco",
      "Pollo",
      "Salsa Curry: (cebolla, ajo, pimentón, curry, sal, leche y nata)",
    ],
    allergens: ["Leche"],
    heating:
      "Calienta en microondas durante 2 a 3 minutos, remueve la salsa y deja reposar 1 minuto antes de servir.",
  },

  {
    slug: "salmon-y-papas",
    name: "Salmón con papas",
    crop: 0,
    image: "assets/meals/salmon-y-papas.JPG",
    calories: 600,
    protein: "44g",
    carbs: "26g",
    fat: "33g",
    labels: ["Pescado", "Alto en proteína", "Rico en Omega-3", "Horno"],
    description:
      "Salmón al horno con papas doradas, pimientos, cebolla y zanahoria.",
    ingredients: [
      "Salmón",
      "Papas",
      "Pimiento rojo",
      "Pimiento verde",
      "Cebolla",
      "Zanahoria",
      "Aceite de oliva",
      "Especias mediterráneas",
    ],
    allergens: ["Pescado"],
    heating:
      "Calienta en microondas durante 2 a 3 minutos o en sartén a fuego medio hasta que el salmón y las papas estén calientes.",
  },

  {
    slug: "pasta-a-la-bolonesa-de-atun",
    name: "Pasta a la boloñesa de atún",
    crop: 0,
    image: "assets/meals/pasta-a-la-bolonesa-de-atun.JPG",
    calories: 540,
    protein: "58g",
    carbs: "37g",
    fat: "15g",
    labels: ["Pescado", "Sin lácteos", "Alto en proteína", "Pasta"],
    description:
      "Pasta penne con boloñesa de atún, salsa de tomate casera y verduras.",
    ingredients: [
      "Pasta penne",
      "Atún",
      "Tomate",
      "Cebolla",
      "Zanahoria",
      "Ajo",
      "Aceite de oliva",
      "Hierbas mediterráneas",
    ],
    allergens: ["Gluten", "Pescado"],
    heating:
      "Calienta en microondas durante 2 a 3 minutos, remueve la salsa y deja reposar 1 minuto antes de servir.",
  },

  {
    slug: "merluza-y-brocoli",
    name: "Merluza y brócoli",
    crop: 0,
    image: "assets/meals/merluza-y-brocoli.JPG",
    calories: 360,
    protein: "42g",
    carbs: "7g",
    fat: "15g",
    labels: ["Pescado", "Bajo en carbohidratos","Bajo en calorías", "Alto en proteína", "Horno"],
    description:
      "Merluza al horno con brócoli asado, aceite de oliva y especias suaves.",
    ingredients: [
      "Merluza",
      "Brócoli",
      "Aceite de oliva",
      "Ajo",
      "Limón",
      "Pimentón dulce",
      "Sal",
      "Pimienta",
    ],
    allergens: ["Pescado"],
    heating:
      "Calienta en microondas durante 2 a 3 minutos o en sartén a fuego medio hasta que la merluza y el brócoli estén calientes.",
  },

  {
    slug: "ternera-molida-y-verduras",
    name: "Ternera molida y verduras",
    crop: 0,
    image: "assets/meals/ternera-molida-y-verduras.JPG",
    calories: 620,
    protein: "48g",
    carbs: "37g",
    fat: "31g",
    labels: ["Alto en proteína", "Sin gluten","Carne de vacuno","Rico en hierro"],
    description:
      "Ternera molida con arroz blanco, pimientos, cebolla y zanahoria salteada.",
    ingredients: [
      "Ternera molida",
      "Arroz blanco",
      "Pimiento rojo",
      "Pimiento verde",
      "Cebolla",
      "Zanahoria",
      "Aceite de oliva",
      "Especias mediterráneas",
    ],
    allergens: ["Sin alérgenos"],
    heating:
      "Calienta en microondas durante 2 a 3 minutos, remueve a mitad de tiempo y deja reposar 1 minuto antes de servir.",
  },

  {
    slug: "pollo-caprese",
    name: "Pollo Caprese",
    crop: 0,
    image: "assets/meals/pollo-caprese.JPG",
    calories: 500,
    protein: "50g",
    carbs: "37g",
    fat: "14g",
    labels: ["Alto en proteína", "Sin gluten","Cocina mediterránea","Rico en vitaminas"],
    description:
      "Pechuga de pollo estilo caprese con arroz blanco, tomate, calabacín y hierbas.",
    ingredients: [
      "Pechuga de pollo",
      "Arroz blanco",
      "Tomate",
      "Calabacín",
      "Aceite de oliva",
      "Albahaca",
      "Orégano",
      "Pimienta",
    ],
    allergens: ["Sin alérgenos"],
    heating:
      "Calienta en microondas durante 2 a 3 minutos o en sartén a fuego medio hasta que el pollo y el arroz estén calientes.",
  },
];
