window.GOOD_MEALS = [
  {
    slug: "pollo-al-curry",
    name: "Pollo al curry",
    crop: 0,
    image: "assets/meals/pollo-al-curry.JPG",
    calories: 610,
    protein: "42g",
    carbs: "51g",
    fat: "24g",
    labels: ["High Protein"],
    description:
      "Pollo al curry con arroz integral, brócoli, zanahoria y salsa de coco.",
    ingredients: [
      "Atlantic salmon",
      "Tri-color quinoa",
      "Avocado",
      "Sweet potato",
      "Cucumber",
      "Red cabbage",
      "Lemon tahini",
    ],
    allergens: ["Gluten", "Apio", "Mostaza", "Lacteos"],
    heating:
      "Remove sauce cup. Microwave for 2 to 3 minutes or heat in a skillet over medium heat until warm.",
  },
  {
    slug: "chicken-pesto-plate",
    name: "Chicken Pesto Plate",
    crop: 1,
    calories: 540,
    protein: "48g",
    carbs: "38g",
    fat: "19g",
    labels: ["High Protein", "Balanced"],
    description:
      "Herb chicken breast with broccolini, basil rice, blistered tomatoes, and pesto.",
    ingredients: [
      "Chicken breast",
      "Broccolini",
      "Basil rice",
      "Cherry tomatoes",
      "Pesto",
      "Parmesan",
    ],
    allergens: ["Milk", "Tree nuts"],
    heating:
      "Microwave covered for 2 minutes, stir rice, then heat 45 seconds more.",
  },
  {
    slug: "vegan-lentil-curry",
    name: "Vegan Lentil Curry",
    crop: 2,
    calories: 580,
    protein: "24g",
    carbs: "79g",
    fat: "16g",
    labels: ["Vegan", "Dairy Free"],
    description:
      "Golden lentil curry with spinach, brown rice, cilantro, and bright lime.",
    ingredients: [
      "Red lentils",
      "Brown rice",
      "Coconut milk",
      "Spinach",
      "Cilantro",
      "Lime",
      "Turmeric",
    ],
    allergens: ["Coconut"],
    heating:
      "Microwave for 3 minutes, stir halfway, and finish with lime after heating.",
  },
  {
    slug: "keto-steak-greens",
    name: "Keto Steak Greens",
    crop: 3,
    calories: 690,
    protein: "52g",
    carbs: "14g",
    fat: "46g",
    labels: ["Keto", "High Protein"],
    description:
      "Sliced steak with arugula, mushrooms, roasted peppers, and charred lemon.",
    ingredients: [
      "Grass-fed steak",
      "Arugula",
      "Mushrooms",
      "Roasted peppers",
      "Herb oil",
      "Lemon",
    ],
    allergens: [],
    heating:
      "Warm steak and vegetables in a skillet for 3 minutes. Keep greens chilled if preferred.",
  },
  {
    slug: "tofu-soba-salad",
    name: "Tofu Soba Salad",
    crop: 4,
    calories: 520,
    protein: "28g",
    carbs: "58g",
    fat: "18g",
    labels: ["Vegan", "Plant Protein"],
    description:
      "Crispy tofu, soba noodles, edamame, cabbage, carrot, and ginger sesame dressing.",
    ingredients: [
      "Tofu",
      "Soba noodles",
      "Edamame",
      "Cabbage",
      "Carrot",
      "Scallion",
      "Ginger sesame dressing",
    ],
    allergens: ["Soy", "Wheat", "Sesame"],
    heating:
      "Enjoy chilled or microwave noodles and tofu for 90 seconds before adding dressing.",
  },
  {
    slug: "turkey-chili-avocado",
    name: "Turkey Chili Avocado",
    crop: 5,
    calories: 640,
    protein: "46g",
    carbs: "44g",
    fat: "28g",
    labels: ["High Protein", "Gluten Free"],
    description:
      "Slow-simmered turkey chili with beans, tomato, poblano, scallion, and avocado.",
    ingredients: [
      "Ground turkey",
      "Kidney beans",
      "Tomatoes",
      "Poblano",
      "Avocado",
      "Scallion",
      "Cumin",
    ],
    allergens: [],
    heating:
      "Microwave chili for 3 minutes, stirring halfway. Add avocado after heating.",
  },
];
