window.GOOD_MEALS = [
  {
    slug: "pollo-al-curry",
    name: "Pollo al curry",
    crop: 0,
    image: "assets/meals/pollo-al-curry.JPG",
    calories: 610,
    protein: "42g",
    carbs: "51g",
    fat: "24g",
    labels: ["High Protein"],
    description:
      "Pollo al curry con arroz integral, brócoli, zanahoria y salsa de coco.",
    ingredients: [
      "Atlantic salmon",
      "Tri-color quinoa",
      "Avocado",
      "Sweet potato",
      "Cucumber",
      "Red cabbage",
      "Lemon tahini",
    ],
    allergens: ["Gluten", "Apio", "Mostaza", "Lacteos"],
    heating:
      "Remove sauce cup. Microwave for 2 to 3 minutes or heat in a skillet over medium heat until warm.",
  },

  {
    slug: "salmon-y-papas",
    name: "Salmón y papas",
    crop: 0,
    image: "assets/meals/salmon-y-papas.JPG",
    calories: 540,
    protein: "48g",
    carbs: "38g",
    fat: "19g",
    labels: ["Pescado", "Alto en proteína"],
    description:
      "Salmón al horno con papas doradas, pimientos, cebolla y zanahoria.",
    ingredients: [
      "Salmón",
      "Papas",
      "Pimiento rojo",
      "Pimiento verde",
      "Cebolla",
      "Zanahoria",
      "Aceite de oliva",
      "Especias mediterráneas",
    ],
    allergens: ["Pescado"],
    heating:
      "Calienta en microondas durante 2 a 3 minutos o en sartén a fuego medio hasta que el salmón y las papas estén calientes.",
  },

  {
    slug: "pasta-a-la-bolonesa-de-atun",
    name: "Pasta a la boloñesa de atún",
    crop: 0,
    image: "assets/meals/pasta-a-la-bolonesa-de-atun.JPG",
    calories: 580,
    protein: "24g",
    carbs: "79g",
    fat: "16g",
    labels: ["Pescado", "Sin lácteos"],
    description:
      "Pasta penne con boloñesa de atún, salsa de tomate casera y verduras.",
    ingredients: [
      "Pasta penne",
      "Atún",
      "Tomate",
      "Cebolla",
      "Zanahoria",
      "Ajo",
      "Aceite de oliva",
      "Hierbas mediterráneas",
    ],
    allergens: ["Gluten", "Pescado"],
    heating:
      "Calienta en microondas durante 2 a 3 minutos, remueve la salsa y deja reposar 1 minuto antes de servir.",
  },

  {
    slug: "merluza-y-brocoli",
    name: "Merluza y brócoli",
    crop: 0,
    image: "assets/meals/merluza-y-brocoli.JPG",
    calories: 430,
    protein: "44g",
    carbs: "18g",
    fat: "14g",
    labels: ["Pescado", "Bajo en carbohidratos"],
    description:
      "Merluza al horno con brócoli asado, aceite de oliva y especias suaves.",
    ingredients: [
      "Merluza",
      "Brócoli",
      "Aceite de oliva",
      "Ajo",
      "Limón",
      "Pimentón dulce",
      "Sal",
      "Pimienta",
    ],
    allergens: ["Pescado"],
    heating:
      "Calienta en microondas durante 2 a 3 minutos o en sartén a fuego medio hasta que la merluza y el brócoli estén calientes.",
  },

  {
    slug: "ternera-molida-y-verduras",
    name: "Ternera molida y verduras",
    crop: 0,
    image: "assets/meals/ternera-molida-y-verduras.JPG",
    calories: 620,
    protein: "45g",
    carbs: "48g",
    fat: "28g",
    labels: ["Alto en proteína", "Sin gluten"],
    description:
      "Ternera molida con arroz blanco, pimientos, cebolla y zanahoria salteada.",
    ingredients: [
      "Ternera molida",
      "Arroz blanco",
      "Pimiento rojo",
      "Pimiento verde",
      "Cebolla",
      "Zanahoria",
      "Aceite de oliva",
      "Especias mediterráneas",
    ],
    allergens: [],
    heating:
      "Calienta en microondas durante 2 a 3 minutos, remueve a mitad de tiempo y deja reposar 1 minuto antes de servir.",
  },
  
  {
    slug: "pollo-caprese",
    name: "Pollo Caprese",
    crop: 0,
    image: "assets/meals/pollo-caprese.JPG",
    calories: 590,
    protein: "47g",
    carbs: "54g",
    fat: "18g",
    labels: ["Alto en proteína", "Sin gluten"],
    description:
      "Pechuga de pollo estilo caprese con arroz blanco, tomate, calabacín y hierbas.",
    ingredients: [
      "Pechuga de pollo",
      "Arroz blanco",
      "Tomate",
      "Calabacín",
      "Aceite de oliva",
      "Albahaca",
      "Orégano",
      "Pimienta",
    ],
    allergens: [],
    heating:
      "Calienta en microondas durante 2 a 3 minutos o en sartén a fuego medio hasta que el pollo y el arroz estén calientes.",
  },
];
